export enum TaskStatusEnum {
  BACK_LOG = 'BACK_LOG',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
  BLOCKED = 'BLOCKED',
}
